
services:


  database:
    image: postgres:16.0
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql



  auth-service:
    image: auth-service
    container_name: auth-service

    build:
      dockerfile: ./services/auth-service/auth-service.Dockerfile
      context: .
    expose:
      - "8081"

    depends_on:
      database:
        condition: service_healthy



  register-service:
    image: register-service
    container_name: register-service
    build:
      dockerfile: ./services/register-service/register-service.Dockerfile
      context: .
    ports:
      -  "8082:8082"
    depends_on:
      database:
        condition: service_healthy



  task-service:
    image: task-service
    container_name: task-service
    build:
      dockerfile: ./services/task-service/task-service.Dockerfile
      context: .
    expose:
      - "8083"
    depends_on:
      database:
        condition: service_healthy



  nginx:
    image: nginx:alpine
    container_name: nginx
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      auth-service:
        condition: service_started
