
services:
  database:
    image: postgres:16.0
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/postgres

  auth-service:
    image: auth-service
    build:
      dockerfile: ./services/auth-service/auth-service.Dockerfile
      context: .
    ports:
      -  "8081:8081"
    depends_on:
      database:
        condition: service_healthy

  register-service:
    image: register-service
    build:
      dockerfile: ./services/register-service/register-service.Dockerfile
      context: .
    ports:
      -  "8082:8082"
    depends_on:
      database:
        condition: service_healthy
  
  task-service:
    image: task-service
    build:
      dockerfile: ./services/task-service/task-service.Dockerfile
      context: .
    ports:
      -  "8083:8083"
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    build:
      dockerfile: ./nginx/Dockerfile
      context: ./nginx/
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 

volumes:
  db:
